### PR TITLE
Adding performance tests for running 30 multiplications on the secp25…

### PR DESCRIPTION
**Pull request by Sajjon**
…6r1 curve.

### CODE REVIEW

**Comment by nsc** [comment]
Hey Sajjon,
thanks for being the first to submit a patch :)
I would love to include the performance tests, but we need to make sure they work on Linux too, which means usually mostly that you have to add the
`static var allTests = ["test_name", test_name]`
to the test class.

Any reason you included the new scheme?

**Comment by Sajjon** [comment]
@nsc  is this the correct format? https://github.com/nsc/SwiftTLS/pull/8/commits/0db46dbe696931491fc93dffb7a572042fe1da54

**Comment by nsc** [comment]
Yes, that is the right format. I just checked on Linux and I the other thing I forgot is that you also have to add the test case to the XCTestManifests.swift file.

Two more things:
Currently the unit tests take about 30 seconds and I run them before I deploy a new test server on swifttls.org. These performance tests are taking 20 minutes or so. So while I would love to have them in the unit test bundle, they should not contribute more than maybe 10 seconds, I think. Do you think you can bring that runtime down and still keep them meaningful? If not maybe we should create an extra performance tests bundle.

Also, I am not sure I understand the reasoning behind the extra scheme. Why would you want your unit tests to run slowly? My current BigInt implementation relies heavily on optimizations taken in -O and is an order of magnitude slower if all the arrays aren't specialized. So the only time I want to run the unit tests against a debug framework is when I want to debug the unit tests.

**Comment by Sajjon** [comment]
@nsc Oh I did not see the `XCTestManifests.swift` file since it was not added to XCode, I added it to Xcode and added it to the test target - any reason why we DONT want that? :) and I added the performance tests to it...

Yes, you are right it is probably best to not use self.measure by default, which performs the tests 10 times. So I commented out that, so one can comment them in in order to perform the measurement. What the measure close does it to run the code inside it 10 times, so this makes the performance tests run in less than 2 mintues instead of 20. How does that sound?

I also restructured the tests a bit, adding them in a folder.

Regarding the use of two separate schemes - you are deviating from the Xcode standard by using the optimization flags for release in the test target. But of course it is needed to use it for computation heavy applications/code - which this is. I found it more prudent/correct to enable exactly this but doing it explicitly using a new separate scheme. Why did Apple by default use no optimization for test target? I assume it is in order to debug the code and assert correctness. So now using the two schemes, we can use `SwiftTLS` when debugging and asserting correctness - conforming to the Apple standard behaviour of the test target. And when we want the tests to run fast we chose the SwiftTLS-Fast scheme from the drop down. 

Does that make sense? But If you dont want it just let me know and I will remove it!

**Comment by nsc** [comment]
Well, now they don't measure anything anymore :)
I think the idea of noticing right away when the implementation got slower is pretty helpful, but I guess one multiplication would do for that, wouldn't it?
I have an elliptic curve test test_sign_someData_verifies which calls multiplyPoint a few times and comes in at a little over one second. So I wouldn't mind measuring one multiplyPoint call per measure. We could even use a different point for each iteration of the measured closure. That shouldn't add more than maybe a few seconds.

About the scheme. I would argue I am deviating from the default for a good reason. Since the optimizations result in a radically different behaviour I *would* like to test those, so I would prefer keeping it simple with just the one scheme.

Also I am not sure about the directory structure. The swift package manager expects a certain layout by default so it knows where to find tests and sources. I already had to change the directory structure I had set up initially in Xcode. So I would not conflate these two issues with another and keep the structure like before for the time being.

Thanks again!

**Pull request closed without merging**
